### ISSUE TITLE
Wooden Barrel Composting not Working on 1.14.2 and more

### ISSUE THREAD

**Issue by ArnyminerZ** [misode/Skymode4#43]
The Wooden Barrel is not working on Minecraft 1.14.2

I am currently using shaders, but I believe that shouldn't affect the mechanism of the datapacks. Maybe resource packs, but this is not the case.

There are some other errors, maybe caused by the id change in 1.13 and 1.14

I append a [Youtube Link](https://youtu.be/gFpOPtVyutc) for reference.

I have an error report:
```
Couldn't read block tag list skymode4:barrel_top from skymode4:tags/blocks/barrel_top.json in data pack Skymode4_Data_Pack.zip com.google.gson.JsonParseException: Unknown value 'minecraft:wall_sign' at zb$a.c(SourceFile:145) at zb$a$$Lambda$2455/1760758733.get(Unknown Source) at java.util.Optional.orElseThrow(Optional.java:290) at zb$a.a(SourceFile:145) at zc.a(SourceFile:103) at zc$$Lambda$2443/1320478463.get(Unknown Source) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Parsing error loading recipe skymode4:red_sand com.google.gson.JsonSyntaxException: Unknown item 'minecraft:rose_red' at beg.a(SourceFile:162) at beg$$Lambda$2463/693598981.get(Unknown Source) at java.util.Optional.orElseThrow(Optional.java:290) at beg.a(SourceFile:162) at beg.a(SourceFile:144) at ben.c(SourceFile:225) at ben.b(SourceFile:24) at ben$a.b(SourceFile:246) at ben$a.a(SourceFile:241) at bek.a(SourceFile:139) at bek.a(SourceFile:61) at xf.b(SourceFile:12) at xf$$Lambda$1661/897049468.run(Unknown Source) at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) at xh.a(SourceFile:71) at xh$$Lambda$1771/560147448.run(Unknown Source) at rh.run(SourceFile:18) at agk.h(ThreadTaskExecutor.java:159) at ago.h(SourceFile:23) at agk.p(ThreadTaskExecutor.java:130) at net.minecraft.server.MinecraftServer.aW(SourceFile:702) at net.minecraft.server.MinecraftServer.p(SourceFile:696) at agk.c(ThreadTaskExecutor.java:143) at net.minecraft.server.MinecraftServer.b(SourceFile:1466) at net.minecraft.server.MinecraftServer.a(SourceFile:450) at dxk.a(IntegratedServer.java:96) at dxk.d(IntegratedServer.java:127) at net.minecraft.server.MinecraftServer.run(SourceFile:605) at java.lang.Thread.run(Thread.java:745)

Couldn't load function at skymode4:functions/modules/trapped_signs/activate.mcfunction java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown block type 'minecraft:sign' at position 23: ...ock ~ ~ ~ <--[HERE] at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown block type 'minecraft:sign' at position 23: ...ock ~ ~ ~ <--[HERE] at ca.a(SourceFile:67) at re.a(SourceFile:152) at re$$Lambda$2831/953418734.apply(Unknown Source) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ... 6 more

Couldn't load function at skymode4:functions/modules/trapped_signs/init.mcfunction java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown criteria 'minecraft.used:minecraft.sign' at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown criteria 'minecraft.used:minecraft.sign' at ca.a(SourceFile:67) at re.a(SourceFile:152) at re$$Lambda$2831/953418734.apply(Unknown Source) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ... 6 more

Couldn't load function at skymode4:functions/modules/trapped_signs/push.mcfunction java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 2: Unknown block type 'minecraft:sign' at position 33: ...ock ~ ~ ~ <--[HERE] at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 2: Unknown block type 'minecraft:sign' at position 33: ...ock ~ ~ ~ <--[HERE] at ca.a(SourceFile:67) at re.a(SourceFile:152) at re$$Lambda$2831/953418734.apply(Unknown Source) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ... 6 more

Couldn't load function at skymode4:functions/modules/trapped_signs/deactivate.mcfunction java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown block type 'minecraft:sign' at position 23: ...ock ~ ~ ~ <--[HERE] at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604) at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown block type 'minecraft:sign' at position 23: ...ock ~ ~ ~ <--[HERE] at ca.a(SourceFile:67) at re.a(SourceFile:152) at re$$Lambda$2831/953418734.apply(Unknown Source) at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ... 6 more

Couldn't read function tag list skymode4:init from skymode4:tags/functions/init.json in data pack Skymode4_Data_Pack.zip com.google.gson.JsonParseException: Unknown value 'skymode4:modules/trapped_signs/init' at zb$a.c(SourceFile:145) at zb$a$$Lambda$2455/1760758733.get(Unknown Source) at java.util.Optional.orElseThrow(Optional.java:290) at zb$a.a(SourceFile:145) at zc.a(SourceFile:103) at zc$$Lambda$2443/1320478463.get(Unknown Source) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Parsing error loading custom advancement minecraft:recipes/recipes: Expected advancement to be a JsonObject, was an array (["de...s"])
```

**Comment by ArnyminerZ** [comment]
Most of the errors are now fixed in the [Pull Request 44](https://github.com/misode/Skymode4/pull/44)
